### ISSUE TITLE
Can the first arg pls be CPU based as in perl5 pls?

### ISSUE THREAD

**Issue by Tux** [tony-o/perl6-bench#5]
As I test on many different systems ranging from 240 MHz to 4.2 GHz, using a count isn't quite useful, so I generally op for the negative value in perl5 which makes it CPU seconds

Bench.new.timethese(-1.5, { ... });

Type check failed in binding $n; expected 'Int' but got 'Rat'
  in method timethese at lib/Bench.pm6:133

**Comment by tony-o** [comment]
@Tux I don't have a way to get CPU seconds yet from perl6 - I need to use a lib and my attempts when I first created this module wouldn't work with win32.  I'll give it another go with that soon

**Comment by azawawi** [comment]
@tony-o Now you have such an API. Please take a look at https://github.com/perlpilot/benchmark/issues/6.

**Comment by tony-o** [comment]
@Tux @azawawi `Telemetry` has now been implemented -

**Comment by tony-o** [comment]
Implemented in e761a92

**Comment by azawawi** [comment]
@tony-o Thanks

**Comment by azawawi** [comment]
I am actually getting this error after trying it out:

```
Cannot resolve caller Real(Telemetry::Period: ); none of these signatures match:
    (Mu:U \v: *%_)
  in method timethis at /home/azawawi/.rakudobrew/moar-master/install/share/perl6/site/sources/3C4F9414C0EF84754837947BDF0E589A35A2F2C1 (Bench) line 159
  in method timethese at /home/azawawi/.rakudobrew/moar-master/install/share/perl6/site/sources/3C4F9414C0EF84754837947BDF0E589A35A2F2C1 (Bench) line 182
  in block <unit> at benchmark/test-msgpack.pl6 line 19
```

rakudo version
```
This is Rakudo version 2017.10-209-g6ec6f1e built on MoarVM version 2017.10-77-gb9a01f7
implementing Perl 6.c.
```

**Comment by tony-o** [comment]
@azawawi what is in `test-msgpack.pl6`?

**Comment by azawawi** [comment]
@tony-o Please see [here](https://github.com/azawawi/perl6-msgpack/blob/master/benchmark/test-msgpack.pl6).

**Comment by tony-o** [comment]
@azawawi  missed one of the conversions for `Telemetry::Period`, check out version `0.1.5`

**Comment by azawawi** [comment]
@tony-o works perfectly 👍 

Thanks for developing such a useful module. Keep up the awesome work 🥇
